name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons:
  animated_text_kit: ^4.2.2
  cloud_firestore: ^4.8.0
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.5
  flutter_chat_bubble: ^2.0.2
  provider: ^6.0.5
  google_fonts: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - images/
